---
- name: Enable firewalld ports
  firewalld:
    port: "{{ item }}-{{ item }}/tcp"
    immediate: true
    permanent: true
    state: enabled
  with_items:
    - 6443
    - 10250
    - 10251
    - 10252
    - 10255
    - 2379
    - 2380
  tags:
    - firewall
  ignore_errors: true

- name: Enable firewalld ports
  firewalld:
    port: 30000-32767/tcp
    immediate: true
    permanent: true
    state: enabled
  ignore_errors: true
  tags:
    - firewall



